/-
# Numerical Analysis: The Bisection Method

This file develops the classical **bisection root-finding method** for continuous
real functions. It contains:

* A definition of a single bisection step
* The recursive sequence of bisection intervals
* Midpoints of these intervals
* A proof that interval lengths shrink to zero
* Convergence of the midpoint sequence to a root
* A quantitative error bound after `n` iterations

This is structured according to mathlib conventions and is intended as a starting
point for a full formalization.
-/

import Mathlib.Topology.Basic
import Mathlib.Data.Real.Basic
import Mathlib.Analysis.Calculus.MeanValue

open scoped Topology
open Filter

noncomputable section

namespace Numerical

structure Interval where
  a : ℝ
  b : ℝ
  h : a ≤ b

@[simp] def midpoint (I : Interval) : ℝ := (I.a + I.b) / 2

def IccOfInterval (I : Interval) : Set ℝ := Set.Icc I.a I.b

/-! ## Bisection Step -/

/-- A single bisection step: given a function `f` and an interval `[a, b]`
with a sign change, return the next subinterval containing the root. -/
def bisectionStep (f : ℝ → ℝ) (I : Interval) : Interval :=
  if h : f I.a * f (midpoint I) ≤ 0 then
    { a := I.a, b := (midpoint I), h : I.a ≤ (midpoint I) := by simp only [midpoint]; linarith[I.h] }
  else
    { a := (midpoint I), b := I.b, h : (midpoint I) ≤ I.b := by simp only [midpoint]; linarith[I.h] }

/-- Length of a real interval. -/
@[simp] def intervalLength (I : Interval) : ℝ := I.b - I.a

/-! ## Recursive interval sequence -/

/-- The `n`-th interval generated by the bisection method. -/
def bisectionInterval (f : ℝ → ℝ) : ℕ → Interval → Interval
  | 0,   I  => I
  | n+1, I  =>
      let next := bisectionStep f I
      bisectionInterval f n next

/-- The midpoint of the `n`-th bisection interval. -/
def bisectionMidpoint (f : ℝ → ℝ) (I : Interval) (n : ℕ) : ℝ :=
  let In := bisectionInterval f n I
  (In.a + In.b) / 2


/-! ## Interval-shrinking lemmas -/

section IntervalShrink

lemma interval_left_le_midpoint (I: Interval) : I.a ≤ midpoint I := by
  simp only [midpoint]
  linarith [I.h]

lemma interval_midpoint_le_right (I: Interval) : midpoint I ≤ I.b := by
  simp only [midpoint]
  linarith [I.h]

/-- The interval length after one bisection step is half the original. -/
lemma intervalLength_bisectionStep (f : ℝ → ℝ) (I: Interval):
    intervalLength (bisectionStep f I) = (I.b - I.a) / 2 := by
  dsimp only [bisectionStep, midpoint, dite_eq_ite, intervalLength]
  by_cases h : f I.a * f (midpoint I) ≤ 0
  all_goals (split; all_goals (ring_nf))

lemma intervalLength_bisectionInterval (f : ℝ → ℝ) (I : Interval) :
  ∀ n : ℕ, intervalLength (bisectionInterval f n I) = intervalLength I / 2^n
:= by
  intro n
  induction n generalizing I with
  | zero => simp only [intervalLength, bisectionInterval, pow_zero, div_one]
  | succ n ih =>
    simp only [bisectionInterval]
    let J := bisectionStep f I
    have ihJ : intervalLength (bisectionInterval f n J) = intervalLength J / 2^n := by exact ih J
    rw [ihJ, intervalLength_bisectionStep, pow_succ, intervalLength]
    exact Eq.symm (div_mul_eq_div_div_swap (I.b - I.a) (2 ^ n) 2)



/-- The interval diameters tend to zero as `n → ∞`. -/
lemma diam_tendsto_zero (f : ℝ → ℝ) (I : Interval) :
  Tendsto (fun n => intervalLength (bisectionInterval f n I))
          atTop (𝓝 0) := by
  simp_rw [intervalLength_bisectionInterval]
  have hs : (fun n => intervalLength I / 2 ^ n) = 
         (fun n => intervalLength I * (1 / 2) ^ n) := by
    ext n
    simp only [intervalLength, one_div, inv_pow]
    exact rfl
  rw [hs]
  have hpow : Tendsto (fun n => (1 / 2 : ℝ) ^ n) atTop (𝓝 0) := by
    apply tendsto_pow_atTop_nhds_zero_of_lt_one _ _
    all_goals (norm_num)
  convert Tendsto.const_mul (intervalLength I) hpow using 1
  rw [mul_zero]

end IntervalShrink


/-! ## Convergence of the bisection method -/

section Convergence

/-- Helper lemma: midpoints of nested intervals stay within bounds -/
lemma midpoint_in_interval (f : ℝ → ℝ) (I : Interval) (n : ℕ) :
    have {a:= a₀, b:= b₀, h:= _} := I
    have {a:= aₙ, b:= bₙ, h:= _} := bisectionInterval f n I
    a₀ ≤ aₙ ∧ aₙ ≤ bₙ ∧ bₙ ≤ b₀ := by
    constructor
    . induction n generalizing I with
      | zero => simp only [bisectionInterval, le_refl]
      | succ n ih => 
      simp only [bisectionInterval]
      . have ihJ := ih (bisectionStep f I)
        have hi : I.a ≤ (bisectionStep f I).a := by      
          rw [bisectionStep]
          by_cases hfp : f I.a * f (midpoint I) ≤ 0
          · -- left interval: new a = old a
            split
            . simp only [le_refl]
            . contradiction
          · -- right interval: new a = midpoint ≥ a
            split
            . contradiction
            . simp only [midpoint]; linarith [I.h]
        apply le_trans hi
        exact ihJ
    . constructor
      . exact (bisectionInterval f n I).h
      . induction n generalizing I with
      | zero => simp only [bisectionInterval, le_refl]
      | succ n ih => 
      simp only [bisectionInterval]
      . have ihJ := ih (bisectionStep f I)
        have hi :  (bisectionStep f I).b ≤ I.b := by      
          -- bisection always shrinks toward the middle:
          -- The new 'a' is either I.a or midpoint(I), both ≥ I.a
          rw [bisectionStep]
          by_cases hfp : f I.a * f (midpoint I) ≤ 0
          · -- left interval: new a = old a
            split
            . simp only [midpoint]; linarith [I.h]
            . contradiction
          · -- right interval: new a = midpoint ≥ a
            split
            . contradiction
            . simp only [le_refl]
        apply le_trans ihJ
        exact hi

/-- The interval produced by one bisection step is contained in the original interval. -/
lemma bisectionStep_subset (f : ℝ → ℝ) (I : Interval) :
  IccOfInterval (bisectionStep f I) ⊆ IccOfInterval I := by
  dsimp only [bisectionStep, midpoint, dite_eq_ite, IccOfInterval]
  by_cases h : f I.a * f (midpoint I) ≤ 0
  · -- left branch: interval is [I.a, m]
    split
    . intro x hx
      exact ⟨hx.1, le_trans hx.2 (interval_midpoint_le_right I)⟩
    . intro x hx
      exact ⟨le_trans (interval_left_le_midpoint I) hx.1, hx.2⟩
  · -- right branch: interval is [m, I.b]
    split
    . intro x hx
      exact ⟨hx.1, le_trans hx.2 (interval_midpoint_le_right I)⟩
    . intro x hx
      exact ⟨le_trans (interval_left_le_midpoint I) hx.1, hx.2⟩

/-- One-step monotonicity: the (n+1)-th interval is contained in the n-th interval,
    for any starting interval `I`. This is proved by induction on `n`, generalized
    over the starting interval. -/
lemma bisectionInterval_one_step_subset (f : ℝ → ℝ) :
  ∀ (n: ℕ) (I : Interval), (IccOfInterval (bisectionInterval f (n + 1) I)) ⊆ (IccOfInterval (bisectionInterval f n I)) := by
  intro n I
  induction n generalizing I with
  | zero =>
    simp only [bisectionInterval]
    exact bisectionStep_subset f I
  | succ n ih =>
    simp only [bisectionInterval]
    exact ih (bisectionStep f I)

lemma bisectionInterval_subset_of_le {f : ℝ → ℝ} (I : Interval) :
  ∀ {k m : ℕ}, k ≤ m -> (IccOfInterval (bisectionInterval f m I)) ⊆ (IccOfInterval (bisectionInterval f k I)) := by
  intros k m hk
  obtain ⟨t, rfl⟩ := (le_iff_exists_add.1 hk)  -- m = k + t
  induction t with
  | zero => simp only [add_zero, subset_refl]
  | succ t ih =>
    have step_sub := bisectionInterval_one_step_subset f (k + t) I
    exact (step_sub.trans (ih (Nat.le_add_right k t)) : _)

lemma midpoint_dist_bound (f : ℝ → ℝ) (I : Interval) (m n : ℕ) :
  |bisectionMidpoint f I m - bisectionMidpoint f I n| ≤
    intervalLength (bisectionInterval f (min m n) I) := by
  -- Set k = min m n
  let k := min m n
  have hk_m : k ≤ m := Nat.min_le_left _ _
  have hk_n : k ≤ n := Nat.min_le_right _ _

  -- Midpoint m lies in interval m
  have mid_m_in_m :
      bisectionMidpoint f I m ∈ IccOfInterval (bisectionInterval f m I) := by
    let J := bisectionInterval f m I
    dsimp only [bisectionMidpoint]
    have h1 : J.a ≤ (J.a + J.b)/2 := by linarith [J.h]
    have h2 : (J.a + J.b)/2 ≤ J.b := by linarith
    exact ⟨h1, h2⟩

  -- Midpoint n lies in interval n
  have mid_n_in_n :
      bisectionMidpoint f I n ∈ IccOfInterval (bisectionInterval f n I) := by
    let J := bisectionInterval f n I
    dsimp only [bisectionMidpoint]
    have h1 : J.a ≤ (J.a + J.b)/2 := by linarith [J.h]
    have h2 : (J.a + J.b)/2 ≤ J.b := by linarith
    exact ⟨h1, h2⟩

  -- interval m ⊆ interval k because k ≤ m
  have sub_mk :
      IccOfInterval (bisectionInterval f m I) ⊆
      IccOfInterval (bisectionInterval f k I) :=
    bisectionInterval_subset_of_le I hk_m

  -- interval n ⊆ interval k because k ≤ n
  have sub_nk :
      IccOfInterval (bisectionInterval f n I) ⊆
      IccOfInterval (bisectionInterval f k I) :=
    bisectionInterval_subset_of_le I hk_n

  -- Therefore both midpoints lie in interval k
  have mid_m_in_k : bisectionMidpoint f I m ∈ IccOfInterval (bisectionInterval f k I) :=
    sub_mk mid_m_in_m
  have mid_n_in_k : bisectionMidpoint f I n ∈ IccOfInterval (bisectionInterval f k I) :=
    sub_nk mid_n_in_n

  -- Unpack interval k
  -- rewrite the midpoint memberships
  simp only [IccOfInterval, Set.mem_Icc] at mid_m_in_k mid_n_in_k
  simp only [intervalLength, ge_iff_le]
  apply abs_le.2 _
  constructor
  all_goals (linarith)

/-- The bisection step preserves the sign-change property:
    if f a * f b ≤ 0 then the new endpoints also have product ≤ 0. -/
lemma bisectionStep_preserve_sign_change {f : ℝ → ℝ} (I : Interval)
  (h : f I.a * f I.b ≤ 0) : f (bisectionStep f I).a * f (bisectionStep f I).b ≤ 0 := by
  dsimp only [bisectionStep, midpoint, dite_eq_ite]
  by_cases hmid : f I.a * f ((I.a + I.b) / 2) ≤ 0
  · -- left branch: (a, midpoint)
    simp only [hmid, ↓reduceIte]
  · -- right branch: (midpoint, b)
    simp only [hmid]
    have hpos : 0 < f I.a * f ((I.a + I.b) / 2) := lt_of_not_ge hmid
    by_cases fa0 : f I.a = 0
    · rw [fa0, zero_mul] at hpos
      norm_num at hpos
    · cases lt_or_gt_of_ne fa0 with
      -- f a > 0
      | inr =>
        have hfb : f I.b ≤ 0 := by
          apply nonpos_of_mul_nonpos_right h
          assumption
        have hfab : 0 ≤ f ((I.a + I.b) / 2) := by
          rw [mul_comm] at hpos
          apply le_of_lt
          apply (pos_of_mul_pos_left hpos)
          linarith
        exact mul_nonpos_of_nonneg_of_nonpos hfab hfb
      -- f a < 0
      | inl =>
        have hfb : 0 ≤ f I.b := by
          apply nonneg_of_mul_nonpos_right h
          assumption
        have hfab : f ((I.a + I.b) / 2) ≤ 0 := by
          apply le_of_lt
          apply (neg_of_mul_pos_right hpos)
          linarith
        exact mul_nonpos_of_nonpos_of_nonneg hfab hfb

lemma bisectionStep_preserve_sign_change_inductive
    (f : ℝ → ℝ) (I₀ : Interval)
    (hroot : f I₀.a * f I₀.b ≤ 0) :
    ∀ n,
      f (bisectionInterval f n I₀).a *
      f (bisectionInterval f n I₀).b ≤ 0 := by
  intro n
  induction n with
  | zero => simpa only [bisectionInterval] using hroot
  | succ n ih =>
    simp only [bisectionInterval]
    have h:= bisectionStep_preserve_sign_change (bisectionInterval f n I₀) ih
    have hn : bisectionStep f (bisectionInterval f n I₀) = bisectionInterval f n (bisectionStep f I₀) := by
      induction n with
      | zero => simp only [bisectionInterval]
      | succ n ih =>
        simp only [bisectionInterval]
        
        have hi : ∀(I: Interval) (k: ℕ), (bisectionStep f (bisectionInterval f k I)) = (bisectionInterval f (k + 1) I) := by
          intro I k
          simp only [bisectionInterval]
          induction k generalizing I with
          | zero => simp only [bisectionInterval]
          | succ k ihk => exact ihk (bisectionStep f I)
        
        exact hi (bisectionStep f I₀) n
    
    rw [hn] at h
    exact h

lemma bisection_cauchy (f : ℝ → ℝ) (I₀ : Interval) :
  CauchySeq (fun n => bisectionMidpoint f I₀ n) := by
  -- Use the metric Cauchy characterization
  apply Metric.cauchySeq_iff'.mpr
  intro ε hε

  -- diam(I_n) → 0 ⇒ ∃ N, ∀ n ≥ N, diam(I_n) < ε
  have ht := diam_tendsto_zero f I₀
  rw [Metric.tendsto_atTop] at ht
  obtain ⟨N, hN⟩ := ht ε hε

  refine ⟨N, ?_⟩
  intro m hm

  -- midpoint distance bound using the interval of index min m N = N
  have hdist := midpoint_dist_bound f I₀ m N
  rw [min_eq_right hm] at hdist
  have hd := (hN N (le_rfl))
  have hdm: dist (bisectionMidpoint f I₀ m) (bisectionMidpoint f I₀ N) = |bisectionMidpoint f I₀ m - bisectionMidpoint f I₀ N| := by rfl
  rw [dist_zero_right] at hd
  rw [hdm]
  apply lt_of_le_of_lt hdist
  exact lt_of_abs_lt hd

lemma bisection_endpoint_a_converges
    (f : ℝ → ℝ) (I₀ : Interval) (x : ℝ)
    (hx_lim : Tendsto (fun n => bisectionMidpoint f I₀ n) atTop (𝓝 x)) :
    Tendsto (fun n => (bisectionInterval f n I₀).a) atTop (𝓝 x) := by
  -- Use metric characterization of convergence
  rw [Metric.tendsto_atTop]
  intro ε hε

  -- Interval length tends to 0 ⇒ find N₁ such that diam(Iₙ) < ε/2
  have hdiam := diam_tendsto_zero f I₀
  rw [Metric.tendsto_atTop] at hdiam
  obtain ⟨N₁, hN₁⟩ := hdiam (ε / 2) (by linarith)

  -- Midpoints converge ⇒ find N₂ such that |midₙ - x| < ε/2
  rw [Metric.tendsto_atTop] at hx_lim
  obtain ⟨N₂, hN₂⟩ := hx_lim (ε / 2) (by linarith)

  -- Take N = max N₁ N₂
  refine ⟨max N₁ N₂, ?_⟩
  intro n hn

  set Iₙ := bisectionInterval f n I₀
  set aₙ := Iₙ.a
  set midₙ := bisectionMidpoint f I₀ n

  -- 1. aₙ ≤ midₙ always
  have ha_le_mid : aₙ ≤ midₙ := by
    dsimp [aₙ, midₙ, Iₙ, bisectionMidpoint, midpoint]
    exact interval_left_le_midpoint _

  -- 2. |aₙ - x| ≤ |aₙ - midₙ| + |midₙ - x|   (triangle inequality)
  have htri : dist aₙ x ≤ dist aₙ midₙ + dist midₙ x := dist_triangle aₙ midₙ x

  -- 3. Bound |aₙ - midₙ| ≤ intervalLength(Iₙ)
  --    (midpoint lies inside interval)
  have hdistm : dist aₙ midₙ ≤ intervalLength Iₙ := by
    dsimp only [dist, intervalLength]
    -- aₙ ≤ midₙ, so aₙ - midₙ ≤ 0, hence |aₙ - midₙ| = midₙ - aₙ
    have hnonpos : aₙ - midₙ ≤ 0 := by linarith [Iₙ.h]
    rw [abs_of_nonpos hnonpos]
    simp only [neg_sub, tsub_le_iff_right, sub_add_cancel, ge_iff_le, aₙ]
    apply interval_midpoint_le_right

  -- 4. For n ≥ N₁ ⇒ intervalLength(Iₙ) < ε/2
  have hI_len : intervalLength Iₙ < ε / 2 := by
    have hnn : dist (intervalLength (bisectionInterval f n I₀)) 0 < ε / 2 := hN₁ n (le_of_max_le_left hn)
    rw [dist_zero_right] at hnn
    exact lt_of_abs_lt hnn

  -- 5. For n ≥ N₂ ⇒ |midₙ - x| < ε/2
  have hmid : dist midₙ x < ε / 2 := by
    apply hN₂ n
    exact le_trans (le_max_right N₁ N₂) hn

  -- 6. Final estimate:
  --    dist(aₙ, x) ≤ dist(aₙ, midₙ) + dist(midₙ, x) < ε/2 + ε/2 = ε
  have hsum : dist aₙ midₙ + dist midₙ x < ε := by linarith

  exact lt_of_le_of_lt htri hsum

lemma bisection_endpoint_b_converges (f : ℝ → ℝ) (I₀ : Interval) (x : ℝ)
  (hx_lim : Tendsto (fun n => bisectionMidpoint f I₀ n) atTop (𝓝 x)) :
  Tendsto (fun n => (bisectionInterval f n I₀).b) atTop (𝓝 x) := by
  -- Use metric characterization of convergence
  rw [Metric.tendsto_atTop]
  intro ε hε

  -- Interval length tends to 0 ⇒ find N₁ such that diam(Iₙ) < ε/2
  have hdiam := diam_tendsto_zero f I₀
  rw [Metric.tendsto_atTop] at hdiam
  obtain ⟨N₁, hN₁⟩ := hdiam (ε / 2) (by linarith)

  -- Midpoints converge ⇒ find N₂ such that |midₙ - x| < ε/2
  rw [Metric.tendsto_atTop] at hx_lim
  obtain ⟨N₂, hN₂⟩ := hx_lim (ε / 2) (by linarith)

  -- Take N = max N₁ N₂
  refine ⟨max N₁ N₂, ?_⟩
  intro n hn

  set Iₙ := bisectionInterval f n I₀
  set bₙ := Iₙ.b
  set midₙ := bisectionMidpoint f I₀ n

  -- 1. midₙ ≤ bₙ always
  have hmid_le_b : midₙ ≤ bₙ := by
    dsimp [bₙ, midₙ, Iₙ, bisectionMidpoint, midpoint]
    exact interval_midpoint_le_right _

  -- 2. |bₙ - x| ≤ |bₙ - midₙ| + |midₙ - x|   (triangle inequality)
  have htri : dist bₙ x ≤ dist bₙ midₙ + dist midₙ x := dist_triangle bₙ midₙ x

  -- 3. Bound |bₙ - midₙ| ≤ intervalLength(Iₙ)
  --    (midpoint lies inside interval)
  have hdistm : dist bₙ midₙ ≤ intervalLength Iₙ := by
    dsimp only [dist, intervalLength]
    -- midₙ ≤ bₙ , so 0 ≤ bₙ - midₙ, hence |bₙ - midₙ| = bₙ - midₙ
    have hpos : 0 ≤ bₙ - midₙ  := by linarith
    rw [abs_of_nonneg hpos]
    refine tsub_le_tsub_left ?_ bₙ
    apply interval_left_le_midpoint _

  -- 4. For n ≥ N₁ ⇒ intervalLength(Iₙ) < ε/2
  have hI_len : intervalLength Iₙ < ε / 2 := by
    have hnn : dist (intervalLength (bisectionInterval f n I₀)) 0 < ε / 2 := hN₁ n (le_of_max_le_left hn)
    rw [dist_zero_right] at hnn
    exact lt_of_abs_lt hnn

  -- 5. For n ≥ N₂ ⇒ |midₙ - x| < ε/2
  have hmid : dist midₙ x < ε / 2 := by
    apply hN₂ n
    exact le_trans (le_max_right N₁ N₂) hn

  -- 6. Final estimate:
  --    dist(bₙ, x) ≤ dist(bₙ, midₙ) + dist(midₙ, x) < ε/2 + ε/2 = ε
  have hsum : dist bₙ midₙ + dist midₙ x < ε := by linarith

  exact lt_of_le_of_lt htri hsum

lemma bisection_fa_endpoint_converges (f : ℝ → ℝ) (hcont : Continuous f)
  (I₀ : Interval) (x : ℝ)
  (ha_conv : Tendsto (fun n => (bisectionInterval f n I₀).a) atTop (𝓝 x)) :
  Tendsto (fun n => f (bisectionInterval f n I₀).a) atTop (𝓝 (f x)) := by
  exact Continuous.tendsto hcont x |>.comp ha_conv

lemma bisection_fb_endpoint_converges (f : ℝ → ℝ) (hcont : Continuous f)
  (I₀ : Interval) (x : ℝ)
  (hb_conv : Tendsto (fun n => (bisectionInterval f n I₀).b) atTop (𝓝 x)) :
  Tendsto (fun n => f (bisectionInterval f n I₀).b) atTop (𝓝 (f x)) := by
  exact Continuous.tendsto hcont x |>.comp hb_conv

lemma bisection_product_limit (f : ℝ → ℝ) (I₀ : Interval) (x : ℝ)
  (fa_conv : Tendsto (fun n => f (bisectionInterval f n I₀).a) atTop (𝓝 (f x)))
  (fb_conv : Tendsto (fun n => f (bisectionInterval f n I₀).b) atTop (𝓝 (f x))) :
  Tendsto (fun n => f (bisectionInterval f n I₀).a * f (bisectionInterval f n I₀).b) 
    atTop (𝓝 (f x * f x)) := by
  exact Tendsto.mul fa_conv fb_conv

lemma bisection_fx_squared_nonpos (f : ℝ → ℝ) (I₀ : Interval)
  (sign_pres : ∀ n, f (bisectionInterval f n I₀).a * f (bisectionInterval f n I₀).b ≤ 0)
  (prod_conv : Tendsto (fun n => f (bisectionInterval f n I₀).a * f (bisectionInterval f n I₀).b) 
    atTop (𝓝 (f x * f x))) :
  f x * f x ≤ 0 := by
  apply le_of_tendsto prod_conv
  filter_upwards with n
  exact sign_pres n

/--
The bisection midpoint sequence converges to the unique point in the nested
interval intersection, which is a root of `f`.
-/
theorem bisection_converges
    {I₀ : Interval} (f : ℝ → ℝ)
    (hcont : Continuous f)
    (hroot : f I₀.a * f I₀.b ≤ 0) :
    ∃ x,
      Tendsto (fun n => bisectionMidpoint f I₀ n) atTop (𝓝 x)
      ∧ f x = 0 := by
  have cauchy := bisection_cauchy f I₀
  obtain ⟨x, hx_lim⟩ := cauchySeq_tendsto_of_complete cauchy
  use x
  constructor
  · exact hx_lim
  · -- Show f x = 0
    have sign_pres := bisectionStep_preserve_sign_change_inductive f I₀ hroot
    have a_conv := bisection_endpoint_a_converges f I₀ x hx_lim
    have b_conv := bisection_endpoint_b_converges f I₀ x hx_lim
    have fa_conv := bisection_fa_endpoint_converges f hcont I₀ x a_conv
    have fb_conv := bisection_fb_endpoint_converges f hcont I₀ x b_conv
    have prod_conv := bisection_product_limit f I₀ x fa_conv fb_conv
    have fx_sq_nonpos := bisection_fx_squared_nonpos f I₀ sign_pres prod_conv
    -- (f x)² ≤ 0, but (f x)² ≥ 0, so (f x)² = 0, hence f x = 0
    have fx_sq_nonneg : 0 ≤ f x * f x := mul_self_nonneg (f x)
    have : f x * f x = 0 := le_antisymm fx_sq_nonpos fx_sq_nonneg
    exact mul_self_eq_zero.mp this

end Convergence


/-! ## Quantitative Bounds -/

/-- Nestedness: the bisection intervals form a decreasing sequence of sets.
    If `k ≤ m`, then the m-th bisection interval is contained in the k-th. -/
lemma nested_intervals_preserve_containment
    {f : ℝ → ℝ} (I : Interval) :
    ∀ {k m : ℕ}, k ≤ m →
      IccOfInterval (bisectionInterval f m I)
        ⊆ IccOfInterval (bisectionInterval f k I) :=
by
  intro k m hkm
  exact bisectionInterval_subset_of_le I hkm

/-- After `n` steps, the bisection approximation differs from any root
in the initial interval by at most `(b₀ - a₀) / 2^(n+1)`. -/
lemma bisection_error_bound
  {f : ℝ → ℝ} {I : Interval}
  (n : ℕ)
  {r : ℝ}
  (hr : r ∈ IccOfInterval (bisectionInterval f n I)) :
  |bisectionMidpoint f I n - r| ≤ intervalLength I / 2^(n+1) := by
  
  -- Let Iₙ be the nth interval
  set Iₙ := bisectionInterval f n I
  set bₙ := Iₙ.b
  set aₙ := Iₙ.a

  simp only [IccOfInterval, Set.mem_Icc] at hr

  have hxy :
      |bisectionMidpoint f I n - r| ≤ intervalLength Iₙ / 2 := by
    apply abs_le.mpr
    constructor
    all_goals (simp only [bisectionMidpoint, intervalLength, tsub_le_iff_right, Iₙ]; linarith)

  have hfinal : |bisectionMidpoint f I n - r| ≤ intervalLength I / 2^(n+1) := by
    have hle : intervalLength I / 2^(n+1) = intervalLength I / 2^n / 2 := by ring_nf
    simp only [intervalLength_bisectionInterval f I n, Iₙ] at hxy
    exact le_of_le_of_eq hxy (id (Eq.symm hle))

  exact hfinal


end Numerical
