/-
# Numerical Analysis: The Bisection Method

This file develops the classical **bisection root-finding method** for continuous
real functions. It contains:

* A definition of a single bisection step
* The recursive sequence of bisection intervals
* Midpoints of these intervals
* A proof that interval lengths shrink to zero
* Convergence of the midpoint sequence to a root
* A quantitative error bound after `n` iterations

This is structured according to mathlib conventions and is intended as a starting
point for a full formalization.
-/

import Mathlib.Topology.Basic
import Mathlib.Data.Real.Basic
import Mathlib.Analysis.Calculus.MeanValue
import Mathlib.Analysis.SpecialFunctions.Pow.Real

open scoped Topology
open Filter

noncomputable section

namespace Numerical

/-! ## Bisection Step -/

/-- A single bisection step: given a function `f` and an interval `[a, b]`
with a sign change, return the next subinterval containing the root. -/
def bisectionStep (f : ℝ → ℝ) (a b : ℝ) : ℝ × ℝ :=
  let m := (a + b) / 2
  if h : f a * f m ≤ 0 then (a, m) else (m, b)

/-- Length of a real interval. -/
@[simp] def intervalLength (I : ℝ × ℝ) : ℝ := I.2 - I.1

/-! ## Recursive interval sequence -/

/-- The `n`-th interval generated by the bisection method. -/
def bisectionInterval (f : ℝ → ℝ) : ℕ → (ℝ × ℝ) → (ℝ × ℝ)
  | 0,     I     => I
  | n+1, (a, b)  =>
      let next := bisectionStep f a b
      bisectionInterval f n next

/-- The midpoint of the `n`-th bisection interval. -/
def bisectionMidpoint (f : ℝ → ℝ) (I : ℝ × ℝ) (n : ℕ) : ℝ :=
  let (aₙ, bₙ) := bisectionInterval f n I
  (aₙ + bₙ) / 2


/-! ## Interval-shrinking lemmas -/

section IntervalShrink

/-- The interval length after one bisection step is half the original. -/
lemma intervalLength_bisectionStep (f : ℝ → ℝ) (a b : ℝ) :
    intervalLength (bisectionStep f a b) = (b - a) / 2 := by
  dsimp [bisectionStep, intervalLength]
  set m : ℝ := (a + b) / 2

  by_cases h : f a * f m ≤ 0
  · -- Case 1: choose interval (a, m)
    simp [h, m]  -- reduces goal to proving: m - a = (b - a)/2
    have : m - a = (b - a) / 2 := by
      simp [m, sub_eq_add_neg, add_comm]
      linarith
    linarith

  · -- Case 2: choose interval (m, b)
    simp [h, m]
    have : b - m = (b - a) / 2 := by
      simp [m, sub_eq_add_neg]
      linarith
    linarith


lemma intervalLength_bisectionInterval (f : ℝ → ℝ) (I : ℝ × ℝ) :
  ∀ n : ℕ, intervalLength (bisectionInterval f n I) = intervalLength I / 2^n
:= by
  intro n
  induction n generalizing I with
  | zero => simp [bisectionInterval, intervalLength, pow_zero]
  | succ n ih =>
    rcases I with ⟨a, b⟩
    -- by definition of bisectionInterval
    simp only [bisectionInterval]
    -- let J be the interval after one bisection step
    let J := bisectionStep f a b
    -- Apply the inductive hypothesis to J (not I!)
    have ih_J : intervalLength (bisectionInterval f n J) = intervalLength J / 2^n := ih J
    rw [ih_J]
    -- Now we need: intervalLength J / 2^n = intervalLength (a, b) / 2^(n+1)
    rw [intervalLength_bisectionStep]
    -- We have: ((b - a) / 2) / 2^n = (b - a) / 2^(n+1)
    simp [intervalLength, pow_succ]
    ring



/-- The interval diameters tend to zero as `n → ∞`. -/
lemma diam_tendsto_zero (f : ℝ → ℝ) (I : ℝ × ℝ) :
  Tendsto (fun n => intervalLength (bisectionInterval f n I))
          atTop (𝓝 0) := by
  simp_rw [intervalLength_bisectionInterval]
  sorry

end IntervalShrink


/-! ## Convergence of the bisection method -/

section Convergence

/-- Helper lemma: midpoints of nested intervals stay within bounds -/
lemma midpoint_in_interval (f : ℝ → ℝ) (I : ℝ × ℝ) (n : ℕ) :
    let (a, b) := I
    let (aₙ, bₙ) := bisectionInterval f n I
    a ≤ aₙ ∧ aₙ ≤ bₙ ∧ bₙ ≤ b := by
  sorry -- This would require additional lemmas about interval nesting

/-- Helper: distance between two midpoints is bounded by interval length -/
lemma midpoint_dist_bound (f : ℝ → ℝ) (I : ℝ × ℝ) (m n : ℕ) :
    |bisectionMidpoint f I m - bisectionMidpoint f I n| ≤ 
    intervalLength (bisectionInterval f (min m n) I) := by
  sorry -- Follows from both midpoints being in the min-th interval

/--
The bisection midpoint sequence converges to the unique point in the nested
interval intersection, which is a root of `f`.
-/
theorem bisection_converges
    {a₀ b₀ : ℝ} (f : ℝ → ℝ)
    (hcont : Continuous f)
    (hroot : f a₀ * f b₀ ≤ 0) :
    ∃ x,
      Tendsto (fun n => bisectionMidpoint f (a₀, b₀) n) atTop (𝓝 x)
      ∧ f x = 0 := by
  -- The key idea: nested intervals with shrinking diameter
  -- By Cantor's nested interval theorem, the intersection is a single point
  
  -- First, show the sequence is Cauchy
  have cauchy : CauchySeq (fun n => bisectionMidpoint f (a₀, b₀) n) := by
    apply Metric.cauchySeq_iff'.mpr
    intro ε hε
    -- Use diam_tendsto_zero to find N where diam < ε
    have := diam_tendsto_zero f (a₀, b₀)
    rw [Metric.tendsto_atTop] at this
    obtain ⟨N, hN⟩ := this ε hε
    use N
    intro m hm
    -- Show |xₘ - xₙ| ≤ diam of interval, which is < ε
    sorry
  
  -- Since ℝ is complete, Cauchy sequence converges
  obtain ⟨x, hx⟩ := cauchySeq_tendsto_of_complete cauchy
  use x
  constructor
  · exact hx
  · -- Show f x = 0 by continuity
    -- Each interval contains a sign change
    -- The limit point must be a root
    sorry -- Would need to show:
    -- 1. f preserves sign change at endpoints of each interval
    -- 2. Endpoints converge to x
    -- 3. Therefore f(x) must be zero by continuity

end Convergence


/-! ## Quantitative Bounds -/

/-- Helper: nested intervals preserve containment -/
lemma nested_intervals_preserve_containment (f : ℝ → ℝ) (I : ℝ × ℝ) (n : ℕ) :
    ∀ x, x ∈ Set.Icc I.1 I.2 → 
    let (aₙ, bₙ) := bisectionInterval f n I
    x ∈ Set.Icc aₙ bₙ := by
  sorry -- Requires proving bisection maintains sign change property

/-- After `n` steps, the bisection approximation differs from any root
in the initial interval by at most `(b₀ - a₀) / 2^(n+1)`. -/
theorem bisection_error_bound
    (f : ℝ → ℝ) (I : ℝ × ℝ) (n : ℕ) :
    let xₙ := bisectionMidpoint f I n
    let (a₀, b₀) := I
    ∀ x ∈ Set.Icc a₀ b₀,
      |xₙ - x| ≤ intervalLength I / (2^(n+1)) := by
  intro x hx
  rcases I with ⟨a₀, b₀⟩
  
  -- Let (aₙ, bₙ) be the n-th interval
  obtain ⟨aₙ, bₙ⟩ := bisectionInterval f n (a₀, b₀)
  set xₙ := (aₙ + bₙ) / 2
  
  -- Key fact: x must be in [aₙ, bₙ] (nested intervals preserve the root)
  have x_in_interval : x ∈ Set.Icc aₙ bₙ := by
    sorry
  
  -- Therefore |xₙ - x| ≤ (bₙ - aₙ) / 2
  have bound_by_half_interval : |xₙ - x| ≤ (bₙ - aₙ) / 2 := by
    have hx_le_b : x ≤ bₙ := x_in_interval.2
    have ha_le_x : aₙ ≤ x := x_in_interval.1
    rw [abs_sub_le_iff]
    constructor
    · -- xₙ - x ≤ (bₙ - aₙ) / 2
      have : xₙ = (aₙ + bₙ) / 2 := rfl
      linarith
    · -- -(bₙ - aₙ) / 2 ≤ xₙ - x
      have : xₙ = (aₙ + bₙ) / 2 := rfl
      linarith
  
  -- Use intervalLength_bisectionInterval: bₙ - aₙ = (b₀ - a₀) / 2^n
  sorry

end Numerical